apiVersion: apps/v1
kind: Deployment
metadata:
  name: gomovie-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gomovie
  template:
    metadata:
      labels:
        app: gomovie
    spec:
      containers:
      - name: gomovie
        image: orsanaw/gomovie-front-image:1.0.2
        ports:
        - containerPort: 80