@Library('shared-library') _
pipeline {
    agent any

    environment {
        DOCKERHUB_REPO = "${env.GOMOVIE_FRONTEND_IMAGE}"
        DOCKERFILE = 'Dockerfile'
        IMAGE_VERSION_FILE = 'version.txt'
    }

    parameters {
        choice(name: 'VERSION_INCREMENT', choices: ['MAJOR', 'MINOR', 'PATCH'], description: 'Select the version part to increment')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Read Current Version') {
            steps {
                script {
                    readCurrentVersion(env.IMAGE_VERSION_FILE, params.VERSION_INCREMENT)
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${env.DOCKERHUB_REPO}:${IMAGE_TAG} -f ${env.DOCKERFILE} ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh "echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin"
                        sh "docker push ${env.DOCKERHUB_REPO}:${IMAGE_TAG}"
                    }
                }
            }
        }

        stage('Update Version File') {
            when {
                expression { currentBuild.result == null || currentBuild.result == 'SUCCESS' }
            }
            steps {
                script {
                    writeFile file: env.IMAGE_VERSION_FILE, text: IMAGE_TAG
                    archiveArtifacts artifacts: env.IMAGE_VERSION_FILE, fingerprint: true
                }
            }
        }
    }

    post {
        success {
            echo "Successfully built and pushed Docker image: ${env.DOCKERHUB_REPO}:${IMAGE_TAG}"
        }
        failure {
            echo "Build failed. Check the logs for details."
        }
    }
}
